### ISSUE TITLE
Failed to check emulator boot status, error: exit status 255

### ISSUE THREAD

**Issue by JolandaVerhoef** [bitrise-steplib/steps-wait-for-android-emulator#8] opened 2018-01-15 09:24 UTC
Today my build failed quite randomly when performing this step. It first fails to wait for the emulator and then complains that it couldn't check the emulator's boot status. Rebuilding fixed it.

**Output:**
```
+------------------------------------------------------------------------------+

| (5) wait-for-android-emulator                                                |
+------------------------------------------------------------------------------+
| id: wait-for-android-emulator                                                |
| version: 1.0.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2018-01-15T08:50:24Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[08:50:24] Start installing (golang) with apt-get       
INFO[08:50:24]  * [OK] Step dependency (go) installed, available. 
Configs:
- emulatorSerial: emulator-5554
- bootTimeout: 300
- AndroidHome: /opt/android-sdk-linux
Waiting for emulator boot
> Checking if device booted...
Running command timed out, retry...
> Checking if device booted...
Failed to check emulator boot status, error: exit status 255
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | wait-for-android-emulator (exit code: 1)                      | 30 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...com/bitrise-steplib/steps-wait-for-android-emulator/issues |
| Source: https://github.com/bitrise-steplib/steps-wait-for-android-emulator   |
+---+---------------------------------------------------------------+----------+
```

**Comment by viktorbenei** [comment] 2018-01-15 10:31
Hi @JolandaVerhoef ,

Thanks for the issue report! Our tooling team will check it ASAP!

**Comment by trapacska** [comment] 2018-02-01 14:54
Hey @JolandaVerhoef 👋

Thank you for reporting the issue! The issue is now fixed in the new version of the step(https://github.com/bitrise-steplib/steps-wait-for-android-emulator/releases/tag/1.0.4)

Closing the issue now, please feel free to re-open if you encounter any issue with the new version.

**Closed by trapacska** 2018-02-01 14:54 UTC
